"""
Dumbo LFSR implementation, per Elephant v2 spec section 2.3.2
and Sarry et al. CARDIS 2023 paper equation (2).

φ_Dumbo: (x_0, ..., x_19) → (x_1, ..., x_19, x_0 ≪ 3 ⊕ x_3 ≪ 7 ⊕ x_13 ≫ 7)

Where:
  - State is 20 bytes (160 bits)
  - ≪ is byte-level left rotation (1 byte = 8 bits)
  - ≪ 7 is left shift by 7 (loses bits)
  - ≫ 7 is right shift by 7

Wait — re-reading the LFSR figure: `x_0 ≪ 3` means 3-bit ROTATION of byte x_0
(rotates within 8 bits). But `x_3 ≪ 7` and `x_13 ≫ 7` are SHIFTS (lose bits).

Actually the original Sarry paper text uses ≪ for rotation in some places
and the spec uses different notation. Let me be careful. The most common
interpretation, supported by the SECRYPT paper:

    x_{j+20} = ROL3(x_j) XOR (x_{j+3} << 7 mod 256) XOR (x_{j+13} >> 7)

ROL3 = rotate-left-by-3-bits within an 8-bit byte (preserves all bits)
<< 7 = arithmetic left shift, only bottom bit survives at top position
>> 7 = arithmetic right shift, only top bit survives at bottom position

This is the implementation we use, matching the official C reference.
"""

import numpy as np


def rol8(b, n):
    """Rotate 8-bit byte left by n positions."""
    n = n % 8
    return ((b << n) | (b >> (8 - n))) & 0xFF


def lfsr_step(state):
    """
    Apply one step of the Dumbo LFSR.
    state: list of 20 ints, each 0..255
    Returns: new state (list of 20 ints)
    """
    x0  = state[0]
    x3  = state[3]
    x13 = state[13]
    new_byte = rol8(x0, 3) ^ ((x3 << 7) & 0xFF) ^ (x13 >> 7)
    return state[1:] + [new_byte]


def lfsr_run(initial_state, num_steps):
    """
    Run the LFSR for num_steps and return all generated bytes.
    initial_state: 20 bytes
    Returns: list of (20 + num_steps) bytes — the full trace
    """
    state = list(initial_state)
    trace = list(state)  # x_0 .. x_19
    for _ in range(num_steps):
        new_byte = (rol8(state[0], 3)
                    ^ ((state[3] << 7) & 0xFF)
                    ^ (state[13] >> 7))
        trace.append(new_byte)
        state = state[1:] + [new_byte]
    return trace


def compute_y_z(x_trace):
    """
    Compute y and z masks from x trace, per equations (9), (10):
      y_j = x_j ⊕ x_{j+1}
      z_j = x_j ⊕ x_{j+2}
    
    Given x_0..x_{n-1}, returns (y_0..y_{n-2}, z_0..z_{n-3})
    """
    y = [x_trace[j] ^ x_trace[j+1] for j in range(len(x_trace)-1)]
    z = [x_trace[j] ^ x_trace[j+2] for j in range(len(x_trace)-2)]
    return y, z


# ─────────── Self-test ───────────

def _selftest():
    # Random initial state
    rng = np.random.default_rng(42)
    init = list(rng.integers(0, 256, size=20).tolist())
    
    # Run LFSR forward
    trace = lfsr_run(init, num_steps=2)
    assert len(trace) == 22
    assert trace[:20] == init
    
    # Verify equation (2) directly
    expected = (rol8(init[0], 3)
                ^ ((init[3] << 7) & 0xFF)
                ^ (init[13] >> 7))
    assert trace[20] == expected, f"LFSR step wrong: got {trace[20]}, expected {expected}"
    
    # y, z computation
    y, z = compute_y_z(trace)
    assert y[0] == trace[0] ^ trace[1]
    assert z[0] == trace[0] ^ trace[2]
    
    return True


if __name__ == "__main__":
    _selftest()
    print("OK — Dumbo LFSR self-tests pass.")
    print()
    print("Demo: 5 steps from random initial state")
    rng = np.random.default_rng(0)
    init = list(rng.integers(0, 256, size=20).tolist())
    trace = lfsr_run(init, num_steps=5)
    print(f"  initial: {init}")
    print(f"  trace[20..24]: {trace[20:25]}")